/*
 * File: YawSpeedPID_External_Functions.h
 *
 * Code generated for Simulink model :YawSpeedPID.
 *
 * Model version      : 1.2
 * Simulink Coder version    : 23.2 (R2023b) 01-Aug-2023
 * TLC version       : 23.2 (Jan 09 2024)
 * C/C++ source code generated on  : Tue Jan  9 22:31:22 2024
 *
 * Target selection: stm32.tlc
 * Embedded hardware selection: Intel->x86-64 (Windows64)
 * Code generation objectives: Unspecified
 * Validation result: Not run
 *
 *
 *
 * ******************************************************************************
 * * attention
 * *
 * * THE PRESENT FIRMWARE WHICH IS FOR GUIDANCE ONLY AIMS AT PROVIDING CUSTOMERS
 * * WITH CODING INFORMATION REGARDING THEIR PRODUCTS IN ORDER FOR THEM TO SAVE
 * * TIME. AS A RESULT, STMICROELECTRONICS SHALL NOT BE HELD LIABLE FOR ANY
 * * DIRECT, INDIRECT OR CONSEQUENTIAL DAMAGES WITH RESPECT TO ANY CLAIMS ARISING
 * * FROM THE CONTENT OF SUCH FIRMWARE AND/OR THE USE MADE BY CUSTOMERS OF THE
 * * CODING INFORMATION CONTAINED HEREIN IN CONNECTION WITH THEIR PRODUCTS.
 * *
 * ******************************************************************************
 */

#ifndef RTW_HEADER_YawSpeedPID_External_Functions_h_
#define RTW_HEADER_YawSpeedPID_External_Functions_h_

/* Generated by STM32_Config.*/
/***** External Imported Functions *****/
#endif                        /* RTW_HEADER_YawSpeedPID_External_Functions_h_ */

/* File trailer for Real-Time Workshop generated code.
 *
 * [EOF] YawSpeedPID_External_Functions.h
 */
